# -*- coding: utf-8 -*-
#
# sample documentation build configuration file, created by
# sphinx-quickstart on Mon Apr 16 21:22:43 2012.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

configData = dict(
    email = 'zz-sasharma@fullerton.edu',
    password = '23811986',
    setLoginCookie = "yes",
    invalidPasswordCount =  0
)

urls = dict(
    mainUrl = "https://www.researchgate.net/",
    login = "https://www.researchgate.net/login",
    search = "https://www.researchgate.net/institution/California_State_University_Fullerton/members?page=1"

)

files = dict(
    facultyURL = "./downloads/facultyurls.txt"
)

